### PR TITLE
fix toast imports

### PR DESCRIPTION
**Pull request by smk762**
Fix for toast color bug reported in RC testing.

To test:
- place an order
- confirm the toast (middle bottom) displays with correct colors

### CODE REVIEW

**Comment by cipig** [comment]
image
my app now looks like this, in dark mode
switching between dark and light does not work any more, the button at the top doesn't do anything
my logs are full of this messages
```
[17:02:08] [info] [timesync.checker.service.cpp:109] [1584627]: System time is in sync: true
[17:02:14] [info] [main.prerequisites.hpp:90] [1584596]: Dex.Themes.CurrentTheme.loadFromFilesystem: loading Default - Dark...
[17:02:14] [info] [qt.utilities.cpp:156] [1584596]: load theme: /home/florian/.atomic_qt/themes/Default - Dark/colors.json
[17:02:14] [error] [main.prerequisites.hpp:96] [1584596]: Default - Dark is broken: Error: Invalid write to global property "colorTheme1". Trying to load a default theme.
[17:02:14] [info] [main.prerequisites.hpp:90] [1584596]: Dex.Themes.CurrentTheme.loadFromFilesystem: loading Default - Light...
[17:02:14] [info] [qt.utilities.cpp:156] [1584596]: load theme: /home/florian/.atomic_qt/themes/Default - Light/colors.json
[17:02:14] [error] [main.prerequisites.hpp:96] [1584596]: Default - Light is broken: Error: Invalid write to global property "colorTheme1". Trying to load a default theme.
[17:02:14] [info] [main.prerequisites.hpp:90] [1584596]: Dex.Themes.CurrentTheme.loadFromFilesystem: loading Default - Light...
[17:02:14] [info] [qt.utilities.cpp:156] [1584596]: load theme: /home/florian/.atomic_qt/themes/Default - Light/colors.json
[17:02:14] [error] [main.prerequisites.hpp:96] [1584596]: Default - Light is broken: Error: Invalid write to global property "colorTheme1". Trying to load a default theme.
[17:02:14] [info] [main.prerequisites.hpp:90] [1584596]: Dex.Themes.CurrentTheme.loadFromFilesystem: loading Default - Light..
```

**Review by ShantanuSharma9873 — COMMENTED** [review]
Same issue as @cipig mentioned. By default in Light mode & the dark mode is not working. 
The Main Screen looks like this, where the Komodo Logo is not visible. 
MainPage_RC_Fix

The Landing page (Portfolio) looks like this. Komodo Logo missing:
LandingPage_RC_Fix

Also, Note that the Toaster is visible Now in the RED Color
https://github.com/user-attachments/assets/f3133b3a-d6b5-4808-aeb6-0fae4c33176a

**Comment by smk762** [comment]
> Also, Note that the Toaster is visible Now in the RED Color https://github.com/user-attachments/assets/f3133b3a-d6b5-4808-aeb6-0fae4c33176a

Red is ok in this case, as it indicates a failed operation

**Review by cipig — APPROVED** [review]
dark mode works again, popup is green when order is placed successfully

**Comment by ShantanuSharma9873** [comment]
The issue is fixed and by default the wallet is in Dark Mode, also both the themes are working fine. 

Issue Observed: After placing an order and swapping coins successfully, they are not reflecting in the Orders & History tabs. 
image

**Pull request merged**
