### PR TITLE
Update app version

### PR DESCRIPTION
**Pull request by smk762**
- Confirm version string in settings is 0.8.0
- Confirm VOTE2024 and all KIP voting chains have been removed

### CODE REVIEW

**Comment by ShantanuSharma9873** [comment]
- The Application Version has been successfully updated to 0.8.0 beta. 
image

- But able to see the 'VOTE2024' at the Add Crypto. Also, the user is able to Enable the coin.
image

**Review by AndrewDelaney — COMMENTED** [review]
Both the Vote 2024 and KIP tokens are still present.
What has changed, though, is that the Vote 2024 asset is no longer added by default.

**Comment by smk762** [comment]
> Both the Vote 2024 and KIP tokens are still present. What has changed, though, is that the Vote 2024 asset is no longer added by default.

They will appear until removed from https://github.com/KomodoPlatform/coins/blob/master/coins#L15642
I'll do the coins repo PR now for this

**Comment by smk762** [comment]
https://github.com/KomodoPlatform/coins/pull/1131

**Review by cipig — DISMISSED** [review]

**Pull request merged**
