### PR TITLE
Release candidate

### PR DESCRIPTION
**Pull request by smk762**

### CODE REVIEW

**Comment by cipig** [comment]
should we switch to mm2 2.3.0? i am already using it in my own Desktop build

**Comment by smk762** [comment]
> should we switch to mm2 2.3.0? i am already using it in my own Desktop build

good catch, though that was already done.

**Review by AndrewDelaney — APPROVED** [review]
I have done a couple rounds of testing on this and have not been able to find any issues.

**Review by ShantanuSharma9873 — APPROVED** [review]
Done with the testing, looks good to me !👍️

**Pull request merged**
