### PR TITLE
v0.7.2 Release Candidate

### PR DESCRIPTION
**Pull request by smk762**
Test all changes from the following PRs:
- #2453 
- #2454 
- #2455 
- #2456 
- #2457 

Also do full regression testing of each page of app to ensure recent changes have not had any unintended consequences.

### CODE REVIEW

**Comment by ShantanuSharma9873** [comment]
image
image
image
image
#2454 Fix. The change in the currency is reflecting at all the places.

**Comment by ShantanuSharma9873** [comment]
image
#2453 Fix. Extended to 8dp for all the Portfolio items.

**Comment by ShantanuSharma9873** [comment]
image
#2457 Fix

**Review by ShantanuSharma9873 — APPROVED** [review]
Tested the fixes, working fine

**Review by AndrewDelaney — APPROVED** [review]
All updates made seem to be working correctly. The following items were tested:
* Confirm that portfolio asset values are all 8 decimal places
* Currency display is changed consistently across the platform according to FIAT setting as well as currency set in top menu.
* Orderbook listings top and bottom are scrolled to match one another as close as possible in the following conditions:
  * flipping pair
  * changing pair
  * changing buy/sell mode
  * loading dex pro tab
* "Show orders after placement" toggle-setting functions correctly, setting the orders tab to either display after making an order or staying on the chart tab accordingly.
* Version is correctly updated to 0.7.2

**Pull request merged**
