### PR TITLE
Zcoin activation date

### PR DESCRIPTION
**Pull request by smk762**
ref: https://github.com/KomodoPlatform/komodo-defi-framework/pull/1922
closes: https://github.com/KomodoPlatform/komodo-wallet-desktop/issues/2354

This PR introduces the `sync_params` feature in the newly released 1.0.7 API. This allows the user to specify which block to begin sync from - previously it was hardcoded as block 1900000 (for ARRR).

image

After this PR is merged it will use the date selected by the user in settings, and where the setting does not exist (e.g. for zombie) it will use 2 days in the past

To test:
- From a clean wallet, activate ARRR.
- Confirm progress % is sane. 
- Select an earlier block from the settings, then restart app and try to activate again. The sync block value for the chosen date should appear in logs like `"first_sync_block":{"actual":1500000,"is_pre_sapling":false,"requested":1500000}`. You dont need to wait for full sync (it takes a long time), just confirm in logs.
- From an older wallet, repeat the above steps.

Note: Balance from transactions prior to the sync block will not be visible / included. Some sections are very, very slow.

### CODE REVIEW

**Comment by kivqa** [comment]
@smk762 I do not observe such entries in logs but code looks working correctly.
I have wallet with ARRR coin and balance 1 ARRR updated on 23 of August.
So I did 2 tests:
1. I used default date for ZHTLC activation date (it's  2 days in the past) in my case it was 9/9/2023
When I tried to activate ARRR coin it takes about 3 minutes and balance was 0.
2. I removed ARRR from Portfolio. Set ZHTLC activation date is 8/1/2023
And then I activated ARRR coin. Activation took about 30 minutes and was completed correctly. Balance for ARRR looks correct (1 ARRR). Transaction for 23 of August displayed correctly. 

All notifications during ARRR activation were displayed correctly.
Logs in mm2.log for ARRR:
```
20:37:25, coins::z_coin::z_rpc:384] INFO Older/Newer sync height detected!, rewinding walletdb to new height: Some(2505086)
 20:37:25, coins::z_coin::z_rpc:871] INFO (Re)starting light_wallet_db_sync_loop for ARRR, blocks per iteration 5000, interval in ms 0

21:10:37, coins_activation::standalone_coin::init_standalone_coin:210] INFO ARRR current block 2564158
```

App log contains following entries for ARRR:
```
[00:10:39] [info] [qt.portfolio.page.cpp:146] [1880582]: initialize_portfolio with tickers: ARRR
[00:10:39] [info] [qt.wallet.manager.cpp:353] [1880582]: Set status: complete
[00:10:39] [info] [qt.portfolio.page.cpp:79] [1880582]: Updating portfolio values with model: true
[00:10:39] [info] [notification.manager.cpp:66] [1880582]: balance update notification: am_i_sender: false amount: 1.00000000 ticker: ARRR human_date: 12 Sep 2023, 00:10
[00:10:42] [info] [mm2.service.cpp:143] [1880582]: Update coins status to: true - field_name: active - tickers: ARRR
```

**Comment by smk762** [comment]
> @smk762 I do not observe such entries in logs but code looks working correctly. API (MM2) version in app 1.0.7-beta_79f6205. I have wallet with ARRR coin and balance 1 ARRR updated on 23 of August. So I did 2 tests:
> 
> 1. I used default date for ZHTLC activation date (it's  2 days in the past) in my case it was 9/9/2023
>    When I tried to activate ARRR coin it takes about 3 minutes and balance was 0.
> 2. I removed ARRR from Portfolio. Set ZHTLC activation date is 8/1/2023
>    And then I activated ARRR coin. Activation took about 30 minutes and was completed correctly. Balance for ARRR looks correct (1 ARRR). Transaction for 23 of August displayed correctly.
> 
> All notifications during ARRR activation were displayed correctly.
> 
> Logs in mm2.log for ARRR:
> 
> ```
> 20:37:25, coins::z_coin::z_rpc:384] INFO Older/Newer sync height detected!, rewinding walletdb to new height: Some(2505086)
>  20:37:25, coins::z_coin::z_rpc:871] INFO (Re)starting light_wallet_db_sync_loop for ARRR, blocks per iteration 5000, interval in ms 0
> 
> 21:10:37, coins_activation::standalone_coin::init_standalone_coin:210] INFO ARRR current block 2564158
> ```
> 
> App log contains following entries for ARRR:
> 
> ```
> [00:10:39] [info] [qt.portfolio.page.cpp:146] [1880582]: initialize_portfolio with tickers: ARRR
> [00:10:39] [info] [qt.wallet.manager.cpp:353] [1880582]: Set status: complete
> [00:10:39] [info] [qt.portfolio.page.cpp:79] [1880582]: Updating portfolio values with model: true
> [00:10:39] [info] [notification.manager.cpp:66] [1880582]: balance update notification: am_i_sender: false amount: 1.00000000 ticker: ARRR human_date: 12 Sep 2023, 00:10
> [00:10:42] [info] [mm2.service.cpp:143] [1880582]: Update coins status to: true - field_name: active - tickers: ARRR
> ```

Cheers - might be the debug logs not showing in "release" builds.

**Review by kivqa — APPROVED** [review]
ARRR coin can be activated with activation date selection.

**Comment by kivqa** [comment]
ARRR coin could be activated successful. Send and swap for ARRR work as expected.
Issue: ARRR activation starts on each app launch

**Comment by smk762** [comment]
> ARRR coin could be activated successful. Send and swap for ARRR work as expected. Issue: ARRR activation starts on each app launch

Subsequent activations will appear to start from scratch (5%) though will complete faster (if same date setting remains).
This is because the activation percentage function is basically when status is:
- `ActivatingCoin` = 5%
- `UpdatingBlocksCache` = between 6% and 50% (current_scanned_block / latest_block * 45 + 5)
- `BuildingWalletDb` = between 51% and 95% (current_scanned_block / latest_block * 45 + 50)
- `RequestingBalance` = 98%

so the percentage value is not a pure indication of `current_scanned_block / latest_block`, it is adaptive to indicate progress over the scan range selected.

**Comment by smk762** [comment]
Here's an indication in CLI of sync duration for a few different timestamps within the last 2 weeks. 

```
smk762@pig:~/mm2_777/activation/z_coin$ ./ARR_by_date.sh 1694390400
{"mmrpc":"2.0","result":{"task_id":0},"id":null}
smk762@pig:~/mm2_777/activation/z_coin$ ./status
Enter task id: 0
[1694982364] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563826,"latest_block":2572454}}},"id":null}
[1694982369] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2566621,"latest_block":2572454}}},"id":null}
[1694982374] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2572343,"latest_block":2572454}}},"id":null}
[1694982379] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563814,"latest_block":2572454}}},"id":null}
[1694982384] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563814,"latest_block":2572454}}},"id":null}
[1694982389] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563814,"latest_block":2572454}}},"id":null}
[1694982394] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563814,"latest_block":2572454}}},"id":null}
[1694982399] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2563814,"latest_block":2572454}}},"id":null}
[1694982404] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2568814,"latest_block":2572454}}},"id":null}
[1694982409] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2568814,"latest_block":2572454}}},"id":null}
[1694982414] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814},"current_scanned_block":2568814,"latest_block":2572454}}},"id":null}
[1694982419] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982424] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982429] {"mmrpc":"2.0","result":{"status":"Ok","details":{"ticker":"ARRR","current_block":2572454,"wallet_balance":{"wallet_type":"Iguana","address":"zs1e3puxpnal8ljjrqlxv4jctlyndxnm5a3mj5rarjvp0qv72hmm9caduxk9asu9kyc6erfx4zsauj","balance":{"spendable":"0","unspendable":"0"}},"first_sync_block":{"requested":2563814,"is_pre_sapling":false,"actual":2563814}}},"id":null}
[1694982434] {"mmrpc":"2.0","error":"No such task '0'","error_path":"init_standalone_coin","error_trace":"init_standalone_coin:133]","error_type":"NoSuchTask","error_data":0,"id":null}
^C
smk762@pig:~/mm2_777/activation/z_coin$ ./ARR_by_date.sh 1694476800
{"mmrpc":"2.0","result":{"task_id":0},"id":null}
smk762@pig:~/mm2_777/activation/z_coin$ ./status
Enter task id: 0
[1694982463] {"mmrpc":"2.0","result":{"status":"InProgress","details":"ActivatingCoin"},"id":null}
[1694982468] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2566706,"latest_block":2572454}}},"id":null}
[1694982473] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2565254,"latest_block":2572454}}},"id":null}
[1694982478] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2565254,"latest_block":2572454}}},"id":null}
[1694982483] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2565254,"latest_block":2572454}}},"id":null}
[1694982488] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2565254,"latest_block":2572454}}},"id":null}
[1694982493] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2570254,"latest_block":2572454}}},"id":null}
[1694982498] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2570254,"latest_block":2572454}}},"id":null}
[1694982503] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254},"current_scanned_block":2570254,"latest_block":2572454}}},"id":null}
[1694982508] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982513] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982518] {"mmrpc":"2.0","result":{"status":"Ok","details":{"ticker":"ARRR","current_block":2572455,"wallet_balance":{"wallet_type":"Iguana","address":"zs1e3puxpnal8ljjrqlxv4jctlyndxnm5a3mj5rarjvp0qv72hmm9caduxk9asu9kyc6erfx4zsauj","balance":{"spendable":"0","unspendable":"0"}},"first_sync_block":{"requested":2565254,"is_pre_sapling":false,"actual":2565254}}},"id":null}
[1694982523] {"mmrpc":"2.0","error":"No such task '0'","error_path":"init_standalone_coin","error_trace":"init_standalone_coin:133]","error_type":"NoSuchTask","error_data":0,"id":null}
^C
smk762@pig:~/mm2_777/activation/z_coin$ ./ARR_by_date.sh 1693699200
curl: (7) Failed to connect to 127.0.0.1 port 7783: Connection refused

smk762@pig:~/mm2_777/activation/z_coin$ ./ARR_by_date.sh 1693699200
{"mmrpc":"2.0","result":{"task_id":0},"id":null}
smk762@pig:~/mm2_777/activation/z_coin$ ./status
Enter task id: 0
[1694982558] {"mmrpc":"2.0","result":{"status":"InProgress","details":"ActivatingCoin"},"id":null}
[1694982563] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2553223,"latest_block":2572455}}},"id":null}
[1694982568] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2556152,"latest_block":2572455}}},"id":null}
[1694982573] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2559052,"latest_block":2572455}}},"id":null}
[1694982578] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562342,"latest_block":2572455}}},"id":null}
[1694982583] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"UpdatingBlocksCache":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2567376,"latest_block":2572455}}},"id":null}
[1694982588] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982593] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982598] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982603] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982608] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982613] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982618] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2552295,"latest_block":2572455}}},"id":null}
[1694982623] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982628] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982633] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982638] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982643] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982648] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982653] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2557295,"latest_block":2572455}}},"id":null}
[1694982658] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562295,"latest_block":2572455}}},"id":null}
[1694982663] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562295,"latest_block":2572455}}},"id":null}
[1694982668] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562295,"latest_block":2572455}}},"id":null}
[1694982673] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562295,"latest_block":2572455}}},"id":null}
[1694982678] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2562295,"latest_block":2572455}}},"id":null}
[1694982684] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2567295,"latest_block":2572455}}},"id":null}
[1694982689] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2567295,"latest_block":2572455}}},"id":null}
[1694982694] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2567295,"latest_block":2572455}}},"id":null}
[1694982699] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2567295,"latest_block":2572455}}},"id":null}
[1694982704] {"mmrpc":"2.0","result":{"status":"InProgress","details":{"BuildingWalletDb":{"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295},"current_scanned_block":2572295,"latest_block":2572455}}},"id":null}
[1694982709] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982714] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982719] {"mmrpc":"2.0","result":{"status":"Ok","details":{"ticker":"ARRR","current_block":2572455,"wallet_balance":{"wallet_type":"Iguana","address":"zs1e3puxpnal8ljjrqlxv4jctlyndxnm5a3mj5rarjvp0qv72hmm9caduxk9asu9kyc6erfx4zsauj","balance":{"spendable":"0","unspendable":"0"}},"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295}}},"id":null}
^C
smk762@pig:~/mm2_777/activation/z_coin$ ./ARR_by_date.sh 1693699200
{"mmrpc":"2.0","result":{"task_id":0},"id":null}
smk762@pig:~/mm2_777/activation/z_coin$ ./status
Enter task id: 0
[1694982729] {"mmrpc":"2.0","result":{"status":"InProgress","details":"ActivatingCoin"},"id":null}
[1694982734] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982739] {"mmrpc":"2.0","result":{"status":"InProgress","details":"RequestingWalletBalance"},"id":null}
[1694982744] {"mmrpc":"2.0","result":{"status":"Ok","details":{"ticker":"ARRR","current_block":2572455,"wallet_balance":{"wallet_type":"Iguana","address":"zs1e3puxpnal8ljjrqlxv4jctlyndxnm5a3mj5rarjvp0qv72hmm9caduxk9asu9kyc6erfx4zsauj","balance":{"spendable":"0","unspendable":"0"}},"first_sync_block":{"requested":2552295,"is_pre_sapling":false,"actual":2552295}}},"id":null}
```

Note the last round, timestamp unchanged but sync much faster than previous sync from same timestamp.

**Review by kivqa — APPROVED** [review]
Approved.
ARRR could be activated and send and swap  functions works as expected. So users are not blocked and can use their funds 
Need to additional enhancement or bug for activation starts on each app launch

**Pull request merged**
