### PR TITLE
Fix dex overflow

### PR DESCRIPTION
**Pull request by smk762**
Closes: https://github.com/KomodoPlatform/komodo-wallet-desktop/issues/2345

This PR also sets min height to 720px (down from 800px), which may introduce some overflows at the bottom of the app. Margins and components have been reduced to accommodate this, though some places may still need work. 

To test:
- Go to dex pro view
- Interact with all elements and confirm no overflows are seen.
- Check all pop up windows in app to confirm working and visually ok (including from outside dex page. E.g. adding coins, viewing orders etc)
- Check any columns where hidden components (e.g. error messages) may result in elements being pushed outside the bottom of the app window.

### CODE REVIEW

**Comment by cipig** [comment]
how about 1366x768 instead of 1280x720? it covers all other resolutions besides 1280x720

**Comment by smk762** [comment]
> how about 1366x768 instead of 1280x720? it covers all other resolutions besides 1280x720. i wonder anyway who uses 1280x720... are there still monitors on Desktop with this low res? mine is 3840x2160 :-)

I'm on 3840x1920 :laughing: 

I chose 1280x720 as the absolute minimum to cover the widest range, there's about 5% of desktop users still with that res. Previously it was 1280*800 so this just reduces height 80px which was simple enough. Setting a different min width has a cascade of updates to do exp in the dex pro page.

The main purpose of this PR tho was to fix overflow on the dex pro page since  the sidebar became "always expanded". I made the sidebar a bit thinner, reduced margins in dex pro view components and fiddled with the chart until it was the right size. 

In future we might increase the min window

**Comment by smk762** [comment]
Also closes: https://github.com/KomodoPlatform/komodo-wallet-desktop/issues/2314

**Review by kivqa — APPROVED** [review]
There is no overlapping or overflow for elements on dex  on my windows VM with screen resolution 1280x800
image
Actually resolution 1280x720 is TV standard know as HD ready. So it's really possible that some users can use their TVs instead of monitors. 
I did not reproduce issues described in #2314

**Pull request merged**
