### PR TITLE
Fix and improve tendermint withdraws

### PR DESCRIPTION
**Pull request by smk762**
This PR adds a warning for Tendermint withdrawals, and adjusts the layout of the send form to include optional IBC channel ID input.

To Test:
- Login and go to send some Tendermint coins
- See warnings about IBC transfers to CEX
- Send tendermint coin with non-IBC transfer (same chain/address format)
- Send tendermint coin with IBC transfer but without custom IBC channel
- Send tendermint coin with IBC transfer and with custom IBC channel
- Confirm link to IBC channel info working
- Test transactions with some other coins to confirm no regression (with/without custom fees & memos)

### CODE REVIEW

**Review by cipig — APPROVED** [review]
thanks for the fix
IRIS withdraws now work fine
image
Sometimes one of the RPCs returns an error, but sends the tx anyway (bg color of error message is fixed):
image

idk which of them returns the error, i have this in my config for IRIS:
```
            {
                "url": "https://iris-rpc.alpha.komodo.earth/",
                "api_url": "https://iris-api.alpha.komodo.earth/",
                "grpc_url": "https://iris-grpc.alpha.komodo.earth/",
                "ws_url": "wss://iris-rpc.alpha.komodo.earth/websocket"
            },
            {
                "url": "https://rpc.irishub-1.irisnet.org"
            }
```
anyway, this is not related to the fix, but to the RPC endpoint

**Comment by cipig** [comment]
the time out comes from `https://iris-rpc.alpha.komodo.earth`, the tx is sent anyway
the other RPC endpoint is even worse, it shows a fee error and does not send anything
guess we need to find some other/more endpoints
what about the ones from https://github.com/cosmos/chain-registry/blob/master/irisnet/chain.json ?

**Comment by cipig** [comment]
tried a second public RPC and i get same error as with `https://rpc.irishub-1.irisnet.org`
image

does our endpoint, `https://iris-rpc.alpha.komodo.earth` have anything special configured in regards to the txfees?

**Review by AndrewDelaney — APPROVED** [review]

**Comment by smk762** [comment]
> tried a second public RPC and i get same error as with `https://rpc.irishub-1.irisnet.org` image
> 
> does our endpoint, `https://iris-rpc.alpha.komodo.earth` have anything special configured in regards to the txfees?

```
minimum-gas-prices = "0.001uiris"
enable-fee-suggestion = false
gas-to-suggest = 200000
denom-to-suggest = "uiris"
```
in app.toml

**Pull request merged**
