### PR TITLE
Fix/bestorders overflow

### PR DESCRIPTION
**Pull request by smk762**
Fixes reported overflow in current RC. 

To test:
- Go to simple dex view
- Select MARTY, then open the buy coin selection list
- Confirm no overflow from tickers or values in columns.

### CODE REVIEW

**Review by ShantanuSharma9873 — COMMENTED** [review]
No details are getting displayed at the dropdown.
image

**Video Attachment:**
https://github.com/user-attachments/assets/c7b31979-3592-4cd7-bdd2-ada0e7e3c264

**Comment by smk762** [comment]
> No details are getting displayed at the dropdown. image
> 
> **Video Attachment:** https://github.com/user-attachments/assets/c7b31979-3592-4cd7-bdd2-ada0e7e3c264

This should be fixed now

**Review by cipig — COMMENTED** [review]
the errors/warning in log are all gone

image
i wonder though where those high values in screenshot are from... selling 12 VRSC in this case

they are not on Pro view, best orders, when selling the same amount of VRSC
image

**Comment by smk762** [comment]
image
The high values are actually low values and technically correct, though a non standard scientific notation.
Will fix

**Comment by ShantanuSharma9873** [comment]
> > No details are getting displayed at the dropdown. image
> > **Video Attachment:** https://github.com/user-attachments/assets/c7b31979-3592-4cd7-bdd2-ada0e7e3c264
> 
> This should be fixed now

The issue is fixed now. Able to see the details perfectly in the dropdown without getting merged. 
image


Observed one issue, where the info is missing to get displayed on the 'Orders' & 'History' tabs after placing an swap order successfully and after completing it. 
image

**Review by cipig — APPROVED** [review]
image
looks good now

**Pull request merged**
